name: dsc
channels:
  - conda-forge
dependencies:
  - python=3.10
  # Core data processing
  - pandas>=1.3.0
  - numpy>=1.20.0
  # Geospatial processing  
  - geopandas>=0.11.1
  - shapely>=1.8.0
  # Network analysis
  - networkx>=2.8.0
  # Scientific computing
  - scipy>=1.7.0
  # Configuration and utilities
  - pyyaml>=5.3.0
  - tqdm>=4.60.0
  # Development tools
  - jupyterlab
  - pytest
