!!python/object:disruptsc.parameters.Parameters
adaptive_inventories: false
adaptive_supplier_weight: false
admin: None
capacity_constraint: 'off'
capital_to_value_added_ratio: 3
combine_sector_cutoff: and
congestion: true
countries_to_include: all
criticality:
  duration: 1
  edges: []
cutoff_firm_output:
  type: absolute
  unit: kUSD
  value: 10
cutoff_household_demand:
  type: absolute
  unit: kUSD
  value: 10
cutoff_sector_demand:
  type: absolute
  unit: mUSD
  value: 1.0
cutoff_sector_output:
  type: absolute
  unit: mUSD
  value: 1.0
destruction_periods:
- 30
- 90
- 180
disruptions: null
epsilon_stop_condition: 0.001
explicit_service_firm: true
export_files: true
export_folder: !!python/object/apply:pathlib._local.WindowsPath
- baseline_capture
- temp_Global_disruption
filepaths:
  admin: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Spatial/admin.geojson
  airways_edges: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Transport/airways_edges.geojson
  countries_spatial: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Spatial/countries.geojson
  firms_spatial: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Spatial/firms.geojson
  households_spatial: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Spatial/households.geojson
  inventory_duration_targets: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Network/inventory_targets.csv
  maritime_edges: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Transport/maritime_edges.geojson
  mrio: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Network/mrio.csv
  multimodal_edges: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Transport/multimodal_edges.geojson
  pipelines_edges: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Transport/pipelines_edges.geojson
  railways_edges: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Transport/railways_edges.geojson
  region_table: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Network/region_table.geojson
  roads_edges: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Transport/roads_edges.geojson
  sector_table: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Network/sector_table.csv
  transport_modes: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Transport/transport_modes.csv
  waterways_edges: !!python/object/apply:pathlib._local.WindowsPath
  - C:\Users\Celian\OneDrive\DisruptSC\disrupt-sc
  - data
  - Global
  - Transport/waterways_edges.geojson
firm_data_type: mrio
flow_data: {}
inventory_duration_targets:
  definition: per_input_type
  unit: day
  values:
    agriculture: 15
    default: 30
    manufacturing: 30
    service: 90
    trade: 30
    transport: 5
    utility: 3
inventory_restoration_time: 4
io_cutoff: 1.0e-05
is_monte_carlo: 0
local_demand_cutoff: 0
logging_level: info
logistics:
  basic_cost:
    airways: 1
    maritime: 0.001
    multimodal: 0.01
    pipelines: 0.0001
    railways: 0.005
    roads: 0.01
    waterways: 0.005
  basic_cost_random: false
  basic_cost_variability:
    airways: 0.01
    maritime: 0.05
    multimodal: 0.01
    pipelines: 0.01
    railways: 0.2
    roads: 0.1
    waterways: 0.2
  border_crossing_fees:
    maritime: 30
    pipelines: 5
    railways: 30
    roads: 30
    waterways: 30
  border_crossing_times:
    maritime: 2
    multimodal: 2
    pipelines: 0
    railways: 2
    roads: 1.5
    waterways: 2
  cost_of_time: 0.49
  dwell_times:
    pipelines-maritime: 6
    railways-maritime: 24
    railways-pipelines: 6
    railways-waterways: 24
    roads-airways: 12
    roads-maritime: 12
    roads-maritime-dom: 12
    roads-pipelines: 6
    roads-railways: 12
    roads-waterways: 12
    waterways-maritime: 24
  loading_fees:
    pipelines-maritime: 1.0
    railways-maritime: 2.2
    railways-pipelines: 1.0
    railways-waterways: 2.2
    roads-airways: 2.2
    roads-maritime: 2.2
    roads-maritime-dom: 2.2
    roads-pipelines: 1.0
    roads-railways: 2.2
    roads-waterways: 2.2
    waterways-maritime: 2.2
  name-specific:
    azerty: 0
  nb_cost_profiles: 1
  sector_types_to_shipment_method:
    agriculture: solid_bulk
    default: container
    mining: solid_bulk
    oil_and_gas: liquid_bulk
  shipment_methods_to_transport_modes:
    container:
    - multimodal
    - roads
    - railways
    - maritime
    - waterways
    - airways
    liquid_bulk:
    - multimodal
    - pipelines
    - roads
    - railways
    - maritime
    - waterways
    - airways
    solid_bulk:
    - multimodal
    - roads
    - railways
    - maritime
    - waterways
    - airways
  speeds:
    airways: 800
    maritime: 35
    pipelines: 50
    railways: 50
    roads: 50
    waterways: 7
  switching_costs:
    modal_switch: 0.15
    port_switch: 0.05
  variability:
    airways: 0.005
    maritime: 0.005
    multimodal:
      pipelines-maritime: 0.1
      railways-maritime: 0.1
      roads-airways: 0.1
      roads-maritime: 0.1
      roads-railways: 0.1
      roads-waterways: 0.1
    railways: 0.02
    roads:
      paved: 0.01
      unpaved: 0.075
    waterways: 0.02
  variability_coef: 0.44
mc_caching:
  agents: true
  logistic_routes: false
  sc_network: false
  transport_network: true
mc_repetitions: 0
min_nb_firms_per_sector: 5
monetary_units_in_data: mUSD
monetary_units_in_model: mUSD
nb_suppliers_per_input: 1
pop_cutoff: 0
pop_density_cutoff: 0
price_increase_threshold: 2
propagate_input_price_change: true
rationing_mode: equal
route_optimization_weight: cost_per_ton
scope: Global
sectors_no_transport_network:
- utility
- transport
- trade
- services
- service
- construction
sectors_to_exclude: None
sectors_to_include: all
sensitivity: null
simulation_type: disruption
t_final: 10
time_resolution: week
transport_capacity_overrides: {}
transport_modes:
- roads
- maritime
transport_to_households: true
use_route_cache: true
utilization_rate: 0.8
weight_localization_firm: 1
weight_localization_household: 4
with_output_folder: true
with_transport: true
