# Indicate the subfolder of the input folder that contains the input files
filepaths:
  "sector_table": "National/59sector_2016_sector_table.csv"
  "tech_coef": "National/59sector_2016_tech_coef.csv"
  "inventory_duration_targets": "National/59sector_inventory_targets.csv"
  "admin_unit_data": "Subnational/59sector_2015_canton_data.geojson"
  "imports": "Trade/59sector_2016_import_table.csv"
  "exports": "Trade/59sector_2016_export_table.csv"
  "transit": "Trade/2016_transit_matrix.csv"
transport_modes: [roads, maritime, waterways, airways]
monetary_units_in_model: mUSD
monetary_units_inputed: kUSD
time_resolution: week
io_cutoff: 0.01
simulation_type: disruption
export_files: True
disruption_description:
  type: compound
  events:
    - item_type: transport_edges
      attribute: id
      values: [465]
      start_time: 1
      duration: 1
    - "item_type": "firms",
      "admin_units": ["1309"],
      "sectors": affected_sectors,
      "start_time": 1,
      "duration": 2,
      "production_capacity_reduction": 0.004153        {
            "item_type": "firms",
            "admin_units": ["1301"],
            "sectors": affected_sectors,
            "start_time": 1,
            "duration": 2,
            "production_capacity_reduction": 0.006068
        },
        {
            "item_type": "firms",
            "admin_units": ["1308"],
            "sectors": affected_sectors,
            "start_time": 1,
            "duration": 2,
            "production_capacity_reduction": 0.007499
        },
        {
            "item_type": "firms",
            "admin_units": ["1321"],
            "sectors": affected_sectors,
            "start_time": 1,
            "duration": 2,
            "production_capacity_reduction": 0.010603
        },
        {
            "item_type": "firms",
            "admin_units": ["1303"],
            "sectors": affected_sectors,
            "start_time": 1,
            "duration": 2,
            "production_capacity_reduction": 0.013404
        },
        {
            "item_type": "firms",
            "admin_units": ["1322"],
            "sectors": affected_sectors,
            "start_time": 1,
            "duration": 2,
            "production_capacity_reduction": 0.022554
        },
        {
            "item_type": "firms",
            "admin_units": ["803"],
            "sectors": affected_sectors,
            "start_time": 1,
            "duration": 2,
            "production_capacity_reduction": 0.116392
        },
        {
            "item_type": "firms",
            "admin_units": ["1320"],
            "sectors": affected_sectors,
            "start_time": 1,
            "duration": 2,
            "production_capacity_reduction": 0.177236

            "item_type": "firms",
            "admin_units": ["1317"],
            "sectors": affected_sectors,
            "start_time": 1,
            "duration": 2,
            "production_capacity_reduction": 0.420373
