# Indicate the subfolder of the input folder that contains the input files
transport_modes: [roads, maritime, waterways, railways]
monetary_units_in_model: mUSD
monetary_units_inputed: USD
time_resolution: week
io_cutoff: 0.04
inventory_duration_targets:
  definition: per_input_type
  values:
    utility: 1
    agriculture: 15
    manufacturing: 30
    service: 90
    trade: 30
    construction: 30
    transport: 3
    default: 30
  unit: day
transport_cost_noise_level: 0
countries_to_include: ['AFR', 'AME', 'ASI', 'EUR', 'OCE', 'THA', 'VNM']
simulation_type: initial_state  # disruption
export_files: False
events:
  - type: transport_disruption
    description_type: edge_attributes
    attribute: disruption_test_1
    values: ["1"]
    start_time: 1
    duration: 1
  - type: transport_disruption
    description_type: edge_attributes
    attribute: disruption_test_1
    values: ["1"]
    start_time: 3
    duration: 2
